server:
  port: 8090
spring:
  data:
    mongodb:
      username: sahil
      password: sahil
      host: localhost
      port: 27017
      database: microservice1
      authentication-database: admin
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: ms2Request:com.microservice.ms1.microservice1.Ms2Requst
